[package]
name = "itoa-fuzz"
version = "0.0.0"
publish = false
edition = "2018"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = { version="0.4", features=["arbitrary-derive"] }

[dependencies.ryu]
path = ".."

# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[[bin]]
name = "fuzz_ryu"
path = "fuzz_targets/fuzz_ryu.rs"
test = false
doc = false
